name = "ControlRL"
uuid = "893554ca-33fa-4dae-9642-08cc5f7da628"
authors = ["Shengjie Xu <shengjiex98@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1.9"
